2.3.4.4.0001/QLVB.WebUI/Controllers/Store/TracuuVanbandiController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using QLVB.Common.Sessions;
using QLVB.Common.Utilities;
using QLVB.DTO.Vanbandi;
using Store.Core.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLVB.WebUI.Controllers.Store
{
    public class TracuuVanbandiController : Controller
    {
        #region Constructor
        private ITracuuVanbandiManager _vanban;
        private ISessionServices _session;


        public TracuuVanbandiController(ITracuuVanbandiManager vanban, ISessionServices session)
        {
            _vanban = vanban;
            _session = session;

        }

        #endregion Constructor

        #region ViewIndex
        public ActionResult Index(bool? isBack)
        {
            if (isBack == true)
            {
                // luu session tim kiem
                //SessionService.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.SearchVBDi);
            }
            else
            {   // khong co isBack (nhan vao menu vanbandi)
                // thi reset session ve Nosearch
                isBack = false;
                _session.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.NoSearch);
            }
            ViewBag.isBack = isBack;

            return View();
        }

        [ChildActionOnly]
        public ActionResult _Toolbar()
        {
            QLVB.DTO.TracuuVanbandi.ToolbarViewModel tbar = _vanban.GetToolbar();
            return PartialView(tbar);
        }


        public ActionResult _ListVanbandi(
            bool? isSearch, bool? isBack,
            string strngaykycat, int? idloaivb, int? idsovb, string strvbphathanh,
            int? intsobd, int? intsokt, string strngaykybd, string strngaykykt,
            string strkyhieu, string strnguoiky, string strnguoisoan, string strnguoiduyet,
            string strnoinhan, string strtrichyeu, string strhantraloi, string strdonvisoan,
            int? idkhan, int? idmat
            )
        {
            SearchVBViewModel model = new SearchVBViewModel();
            //===============================================
            // status
            //===============================================
            model.isSearch = isSearch == true ? true : false;
            model.isBack = isBack == true ? true : false;

            int intPage = 1;
            if (isBack == true)
            {   // tra ve page dang xem khi quay lai
                int _PageType = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchPageType));
                if (_PageType == (int)EnumSession.PageType.VBDi)
                {
                    intPage = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchPageValues));
                }
            }
            model.intPage = intPage;

            if (isSearch == true)
            {
                // khi nhan nut tim kiem thi reset ve Nosearch 
                // de tim theo dieu kien moi
                _session.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.NoSearch);
            }
            //===============================================
            // category
            //===============================================
            model.idsovb = idsovb;//!= null ? (int)idsovb : 0;
            model.idloaivb = idloaivb;//!= null ? (int)idloaivb : 0;            
            model.strngaykycat = strngaykycat;
            model.strvbphathanh = strvbphathanh;
            //===============================================
            // search
            //===============================================
            model.intsobd = intsobd;
            model.intsokt = intsokt;

            model.strngaykybd = strngaykybd;
            model.strngaykykt = strngaykykt;

            model.strkyhieu = strkyhieu;
            model.strnguoiky = strnguoiky;
            model.strnguoiduyet = strnguoiduyet;
            model.strnguoisoan = strnguoisoan;

            model.strnoinhan = strnoinhan;
            model.strtrichyeu = strtrichyeu;

            model.strhantraloi = strhantraloi;
            model.strdonvisoan = strdonvisoan;

            model.idkhan = idkhan;
            model.idmat = idmat;

            return PartialView(model);

        }

        public ActionResult Vanbandi_Read(
            [DataSourceRequest]DataSourceRequest request,
            string strngaykycat, int? idloaivb, int? idsovb, string strvbphathanh,
            int? intsobd, int? intsokt, string strngaykybd, string strngaykykt,
            string strkyhieu, string strnguoiky, string strnguoisoan, string strnguoiduyet,
            string strnoinhan, string strtrichyeu, string strhantraloi, string strdonvisoan,
             int? idkhan, int? idmat
            )
        {
            int currentPage = request.Page;
            string highlightResult = string.Empty;
            // luu trang dang xem vao session
            //_session.InsertObject(AppConts.SessionSearchPageType, EnumSession.PageType.VBDi);
            //_session.InsertObject(AppConts.SessionSearchPageValues, currentPage);

            IEnumerable<ListVanbandiViewModel> vbdi;

            int _SearchType = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchType));
            if (_SearchType == (int)EnumSession.SearchType.SearchTracuuVBDi)
            {
                // lay cac gia tri search trong session
                string strSearchValues = _session.GetObject(AppConts.SessionSearchTypeValues).ToString();

                int _idloaivb = _session.GetIntSearchValues("idloaivb", strSearchValues);
                int _idsovb = _session.GetIntSearchValues("idsovb", strSearchValues);
                string _strngaykycat = _session.GetStringSearchValues("strngaykycat", strSearchValues);
                string _strvbphathanh = _session.GetStringSearchValues("strvbphathanh", strSearchValues);

                int _intsobd = _session.GetIntSearchValues("intsobd", strSearchValues);
                int _intsokt = _session.GetIntSearchValues("intsokt", strSearchValues);
                string _strngaykybd = _session.GetStringSearchValues("strngaykybd", strSearchValues);
                string _strngaykykt = _session.GetStringSearchValues("strngaykykt", strSearchValues);
                string _strkyhieu = _session.GetStringSearchValues("strkyhieu", strSearchValues);
                string _strnguoiky = _session.GetStringSearchValues("strnguoiky", strSearchValues);
                string _strnguoisoan = _session.GetStringSearchValues("strnguoisoan", strSearchValues);
                string _strnguoiduyet = _session.GetStringSearchValues("strnguoiduyet", strSearchValues);

                string _strtrichyeu = _session.GetStringSearchValues("strtrichyeu", strSearchValues);
                string _strnoinhan = _session.GetStringSearchValues("strnoinhan", strSearchValues);
                string _strhantraloi = _session.GetStringSearchValues("strhantraloi", strSearchValues);
                string _strdonvisoan = _session.GetStringSearchValues("strdonvisoan", strSearchValues);

                int _idkhan = _session.GetIntSearchValues("idkhan", strSearchValues);
                int _idmat = _session.GetIntSearchValues("idmat", strSearchValues);

                highlightResult = _strtrichyeu;
                vbdi = _GetListvanban(
                        _strngaykycat, _idloaivb, _idsovb, _strvbphathanh,
                        _intsobd, _intsokt, _strngaykybd, _strngaykykt,
                        _strkyhieu, _strnguoiky, _strnguoisoan, _strnguoiduyet,
                        _strnoinhan, _strtrichyeu, _strhantraloi, _strdonvisoan,
                        _idkhan, _idmat
                    );
            }
            else
            {
                highlightResult = strtrichyeu;
                // khong co luu tim kiem
                vbdi = _GetListvanban(
                        strngaykycat, idloaivb, idsovb, strvbphathanh,
                        intsobd, intsokt, strngaykybd, strngaykykt,
                        strkyhieu, strnguoiky, strnguoisoan, strnguoiduyet,
                        strnoinhan, strtrichyeu, strhantraloi, strdonvisoan,
                        idkhan, idmat
                    );
            }
            DataSourceResult result = vbdi.OrderByDescending(p => p.dtengayky)
                                            .ThenByDescending(p => p.intso)
                                            .ToDataSourceResult(request);


            return Json(result);
        }

        private IEnumerable<ListVanbandiViewModel> _GetListvanban(
            string strngaykycat, int? idloaivb, int? idsovb, string strvbphathanh,
            int? intsobd, int? intsokt, string strngaykybd, string strngaykykt,
            string strkyhieu, string strnguoiky, string strnguoisoan, string strnguoiduyet,
            string strnoinhan, string strtrichyeu, string strhantraloi, string strdonvisoan,
             int? idkhan, int? idmat
            )
        {
            return _vanban.GetListVanbandi(
                    strngaykycat, idloaivb, idsovb, strvbphathanh,
                    intsobd, intsokt, strngaykybd, strngaykykt,
                    strkyhieu, strnguoiky, strnguoisoan, strnguoiduyet,
                    strnoinhan, strtrichyeu, strhantraloi, strdonvisoan,
                    idkhan, idmat
                );
        }

        public ActionResult _SearchVBDi()
        {
            SearchVBViewModel model = _vanban.GetViewSearch();
            return PartialView(model);
        }

        #endregion ViewIndex

        #region ViewDetail

        public ActionResult _ViewDetailVBDi()
        {
            return PartialView();
        }

        public ActionResult _XemChitietVanban(int id)
        {
            DetailVBDiViewModel model = new DetailVBDiViewModel();
            if (id != 0)
            {
                model = _vanban.GetViewDetail(id);
            }

2.3.4.4.0001/QLVB.WebUI/Views/TracuuVanbandi/Index.cshtml
@{
    ViewBag.Title = "Văn bản đi";
    bool isBack = ViewBag.isBack;
    string NamTraCuu = QLVB.Common.Utilities.AppSettings.NamTraCuuVanban;
}

@section header{
	<i class="glyphicon glyphicon-file">&nbsp;</i>Tra cứu Văn bản đi năm @NamTraCuu
}
@Html.Action("_Toolbar")
<div class="row">	
	<div class="col-sm-12 col-md-12" id="listvanbandi">
		@Html.Action("_ListVanbandi", new { isBack = isBack })
	</div>
	@Html.Hidden("idvanban")
</div>
<script type="text/javascript">
	function onChange(arg) {
		var selected = $.map(this.select(), function (item) {
			var value = $(item).text();
			var grid = $("#grid").data("kendoGrid");
			var row = grid.select();
			var intid = grid.dataItem(row).intid;
			var inttrangthai = grid.dataItem(row).inttrangthai;
			SetIdVanban(intid);			
			var currentPage = grid.dataSource.page();
			
		});
	}
	function onDataBound(arg) {
		dataView = this.dataSource.view();
		for (var i = 0; i < dataView.length; i++) {
			if (dataView[i].inttrangthai == 0) {
				var uid = dataView[i].uid;
				$("#grid tbody").find("tr[data-uid=" + uid + "]").addClass("chuaduyet");
			}
		}
	}
	
	function SetIdVanban(idvanban) {
		$('#idvanban').val(idvanban);
	}
	function GetIdVanban() {
		return $('#idvanban').val();
	}

	function ViewDetailVBDi(id) {
		OpenViewDetailVBDi(id);
	}	
</script>
@Html.Action("_ViewDetailVBDi", "TracuuVanbandi")
@Html.Action("_ViewDetailVBDen", "TracuuVanbanden")
@Html.Action("_ViewDetailHoso", "TracuuHoso")

@Html.Action("_SearchVBDi", "TracuuVanbandi")

2.3.4.4.0001/QLVB.WebUI/Views/TracuuVanbandi/_ListVanbandi.cshtml
@model QLVB.DTO.Vanbandi.SearchVBViewModel
@using QLVB.DTO

@(Html.Kendo().Grid<QLVB.DTO.Vanbandi.ListVanbandiViewModel>()
    .Name("grid").AutoBind(false)
    .Columns(columns =>
    {
        columns.Bound(c => c.intid).Hidden();
        columns.Bound(o => o.IsAttach).Title(" ")
            .ClientTemplate(
                "#if (IsAttach) { #" +
                    "<img onclick='ViewDetailVBDi(" + "#= intid #" + ")' alt='#= intid #' src='" + Url.Content("~/Content/Images/noidung_attach.gif") + "' />" +
                "# } else { #" +
                    "<img onclick='ViewDetailVBDi(" + "#= intid #" + ")' alt='#= intid #' src='" + Url.Content("~/Content/Images/noidung.gif") + "' />" +
                "# } #"
            )
            .Width(28);
        columns.Bound(o => o.dtengayky).Format("{0:dd/MM/yyyy}").Title("Ngày ký").Width(90);
        columns.Bound(o => o.intso).Title("Số")
            .ClientTemplate(
                "#if (intso>0) { #" +
                     "#=intso##=strsophu#" +
                "# } #"
                )
            .Width(60);
        columns.Bound(o => o.strkyhieu).Title("Ký hiệu").Width("12%");
        columns.Bound(o => o.strtrichyeu).Title("Trích yếu nội dung").Width("30%").Encoded(false);
        columns.Bound(o => o.strnoinhan).Title("Nơi nhận").Width("20%");
        columns.Bound(o => o.inttrangthai).Hidden();
        columns.Bound(o => o.dtehanxuly).Format("{0:dd/MM/yyyy}").Title("Hạn trả lời").Width(90);
    })
    .HtmlAttributes(new { style = "white-space: normal" })
    .Scrollable()
        //.Sortable()
    .Selectable()
    .Resizable(resize => resize.Columns(true))
    .Pageable(pageable => pageable
        .Refresh(true)
        //.PageSizes(true)
        .ButtonCount(5)
        .Messages(ms => ms.Display(KendoGridDisplay.PageDisplay).Empty(KendoGridDisplay.PageEmpty)
            .First(KendoGridDisplay.PageFirst).Previous(KendoGridDisplay.PagePrevious)
            .Next(KendoGridDisplay.PageNext).Last(KendoGridDisplay.PageLast))
        )
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(QLVB.Common.Utilities.AppSettings.DisplayItemsPerPage)
            .Read(read => read.Action("Vanbandi_Read", "TracuuVanbandi",
                new
                {
                    idsovb = Model.idsovb,
                    idloaivb = Model.idloaivb,
                    strngaykycat = Model.strngaykycat,
                    strvbphathanh = Model.strvbphathanh,
                    intsobd = Model.intsobd,
                    intsokt = Model.intsokt,
                    strngaykybd = Model.strngaykybd,
                    strngaykykt = Model.strngaykykt,
                    strkyhieu = Model.strkyhieu,
                    strnguoiky = Model.strnguoiky,
                    strnguoisoan = Model.strnguoisoan,
                    strnguoiduyet = Model.strnguoiduyet,
                    strnoinhan = Model.strnoinhan,
                    strtrichyeu = Model.strtrichyeu,
                    strhantraloi = Model.strhantraloi,
                    strdonvisoan = Model.strdonvisoan,
                    idkhan = Model.idkhan,
                    idmat = Model.idmat
                })
            )
            .Events(events => events.Error("onError"))
        )
        .Events(events => events.Change("onChange").DataBound("onDataBound"))
)

<script type="text/javascript">
    $(function () {
        dataSource = $('#grid').data().kendoGrid.dataSource;
        dataSource.query({
            page: '@Model.intPage',
            group: dataSource.group(),
            filter: dataSource.filter(),
            sort: dataSource.sort(),
            pageSize: dataSource.pageSize()
        })
    })
    $(window).resize(function () {
        SetGridHeight();
    });
    $(document).ready(function () {
        SetGridHeight();
    })
    function onError(e, status) {
        SetThongbao("Đã có lỗi xảy ra trên Server!");
    }
</script>

2.3.4.4.0001/QLVB.WebUI/Views/TracuuVanbandi/_SearchVBDi.cshtml
@model QLVB.DTO.Vanbandi.SearchVBViewModel

@{
	SelectList ListSovanban = new SelectList(Model.Sovanban, "intid", "strten");
	SelectList ListLoaivanban = new SelectList(Model.Loaivanban, "intid", "strtenvanban");
}

@(Html.Kendo().Window()
	.Name("SearchVBDi")
	.Draggable()
	.AutoFocus(true)
	.Title("Tìm kiếm văn bản đi")
	.Resizable()
	.Width(670)
	.Height(500)
	.Visible(false)
	.Actions(actions => actions.Minimize().Maximize().Close())
	.Content(
	@<text>
		<div id="detail-SearchVBDi">
			<div class="box">
				<header>
					<nav style="padding: 3px;">
						<button id="SubmitSearchVBDibtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-search"></i>&nbsp;Tìm kiếm</button>
						<button id="BackSearchVBDibtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>
						<button id="RefreshSearchVBDibtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-refresh"></i>&nbsp;Refresh</button>

					</nav>
				</header>
			</div>
			<form class="form-horizontal" id="formSearchVBDi">
				@Html.Hidden("isSearch", true)
				<table class="table table-condensed table-bordered responsive-table">
					<tbody>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Số phát hành", new { @class = "font-label" })</td>
							<td>@Html.TextBoxFor(m => m.intsobd, null, new { @class = "form-control form-control-window2 ", placeholder = "" })</td>
							<td class="table-col-4" style="text-align:center;">@Html.Label("==>", new { @class = "font-label" })</td>
							<td>@Html.TextBoxFor(m => m.intsokt, null, new { @class = "form-control form-control-window2 ", placeholder = "" })</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Ngày ký", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DatePicker()
									.Name("strngaykybd")
									.HtmlAttributes(new { style = "width:100%;" })
									.Format("dd/MM/yyyy")
								)
							</td>
							<td class="table-col-4" style="text-align:center;">@Html.Label("==>", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DatePicker()
									.Name("strngaykykt")
									.HtmlAttributes(new { style = "width:100%;" })
									.Format("dd/MM/yyyy")
								)
							</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Ký hiệu", new { @class = "font-label" })</td>
							<td>@Html.TextBox("strkyhieu", null, new { @class = "form-control form-control-window2 ", placeholder = "Ký hiệu" })</td>
							<td class="table-label table-col-4" style="text-align:center;">@Html.Label("Loại văn bản", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DropDownList()
									.Name("idloaivb")
									.BindTo(Model.Loaivanban)
									.DataTextField("strtenvanban")
									.DataValueField("intid")
									.HtmlAttributes(new { @style = "width:100%;" })
									.OptionLabel(" ")
								)
							</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Người ký", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().AutoComplete()
								.Name("strnguoiky")
								.Filter(FilterType.Contains)
								.Placeholder("Người ký")
								.BindTo(Model.Nguoixuly.Select(u => u.strhoten))
								.HtmlAttributes(new { @class = "form-control", style = "width:100%;" })
								.HighlightFirst(true)
								.IgnoreCase(true)
								)
							</td>
							<td class="table-label table-col-4">@Html.Label("Sổ văn bản", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DropDownList()
									.Name("idsovb")
									.BindTo(Model.Sovanban)
									.DataTextField("strten")
									.DataValueField("intid")
									.HtmlAttributes(new { @style = "width:100%;" })
									.OptionLabel(" ")
								)
							</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Độ khẩn", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DropDownList()
									.Name("idkhan")
									.BindTo(Model.Vanbankhan)
									.DataTextField("strtentinhchatvb")
									.DataValueField("intid")
									.HtmlAttributes(new { @style = "width:100%;" })
									.OptionLabel(" ")
								)
							</td>
							<td class="table-label table-col-4">@Html.Label("Độ mật", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DropDownList()
									.Name("idmat")
									.BindTo(Model.Vanbanmat)
									.DataTextField("strtentinhchatvb")
									.DataValueField("intid")
									.HtmlAttributes(new { @style = "width:100%;" })
									.OptionLabel(" ")
								)
							</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Người soạn", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().AutoComplete()
								.Name("strnguoisoan")
								.Filter(FilterType.Contains)
								.Placeholder("Người soạn")
								.BindTo(Model.Nguoixuly.Select(u => u.strhoten))
								.HtmlAttributes(new { @class = "form-control", style = "width:100%;" })
								.HighlightFirst(true)
								.IgnoreCase(true)
								)
							</td>
							<td class="table-label table-col-4">@Html.Label("Người duyệt", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().AutoComplete()
								.Name("strnguoiduyet")
								.Filter(FilterType.Contains)
								.Placeholder("Người duyệt")
								.BindTo(Model.Nguoixuly.Select(u => u.strhoten))
								.HtmlAttributes(new { @class = "form-control", style = "width:100%;" })
								.HighlightFirst(true)
								.IgnoreCase(true)
								)
							</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Nơi nhận", new { @class = "font-label" })</td>
							<td colspan="3">@Html.TextBox("strnoinhan", null, new { @class = "form-control form-control-window ", placeholder = "Cơ quan phát hành" })</td>

						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Trích yếu", new { @class = "font-label" })</td>
							<td colspan="3">@Html.TextBox("strtrichyeu", null, new { @class = "form-control form-control-window ", placeholder = "Trích yếu văn bản" })</td>
						</tr>
						<tr>
							<td class="table-label table-col-4">@Html.Label("Hạn trả lời", new { @class = "font-label" })</td>
							<td>
								@(Html.Kendo().DatePicker()
									.Name("strhantraloi")
									.HtmlAttributes(new { style = "width:100%;" })
									.Format("dd/MM/yyyy")
								)
							</td>
							<td class="table-label table-col-4">@Html.Label("Đơn vị soạn", new { @class = "font-label" })</td>
							<td>
								@Html.TextBox("strdonvisoan", null, new { @class = "form-control form-control-window2 ", placeholder = "Đơn vị soạn" })
							</td>
						</tr>

					</tbody>
				</table>
			</form>
		</div>
	</text>
	)
)

<script type="text/javascript">

	function CloseSearchVBDi() {
		var window = $("#SearchVBDi").data("kendoWindow");
		window.close();
	}
	function OpenSearchVBDi() {
		ResetFormVBDi();
		var window = $("#SearchVBDi").data("kendoWindow");
		window.center();
		window.open();
		setTimeout(function () { $('#intsobd').focus(); }, 1000);
	}
	$('#BackSearchVBDibtn').click(function () {
		CloseSearchVBDi();
	})
	$('#formSearchVBDi').on("keypress", function (e) {
		if (e.keyCode == 13) {
			//alert("Enter pressed");
			SubmitSearchVBDi();
			return false; // prevent the button click from happening
		}
	});
	$('#SubmitSearchVBDibtn').click(function () {
		SubmitSearchVBDi();
	})
	function SubmitSearchVBDi() {
		var collection = $('#formSearchVBDi').serialize();
		var url = '@Url.Action("_Listvanbandi", "TracuuVanbandi")';
		url = url + "?" + collection;
		$('#listvanbandi').load(url);
		CloseSearchVBDi();
	}
	$('#RefreshSearchVBDibtn').click(function () {
		ResetFormVBDi();
	})
	function ResetFormVBDi() {
		$("input").val('');
		$("#isSearch").val('True');
		var dropdownlist = $("#idloaivb").data("kendoDropDownList");
		dropdownlist.select(0);
		var dropdown_sovb = $("#idsovb").data("kendoDropDownList");
		dropdown_sovb.select(0);
		var dropdownlist_khan = $("#idkhan").data("kendoDropDownList");
		dropdownlist_khan.select(0);
		var dropdown_mat = $("#idmat").data("kendoDropDownList");
		dropdown_mat.select(0);
	}
	$('#strngaykybd').keyup(function () {
		var ngay = $('#strngaykybd').val();
		var _ngay = editdate(ngay);
		$('#strngaykybd').val(_ngay);
	})
	$('#strngaykykt').keyup(function () {
		var ngay = $('#strngaykykt').val();
		var _ngay = editdate(ngay);
		$('#strngaykykt').val(_ngay);
	})
	$('#strhantraloi').keyup(function () {
		var ngay = $('#strhantraloi').val();
		var _ngay = editdate(ngay);
		$('#strhantraloi').val(_ngay);
	})
</script>

2.3.4.4.0001/QLVB.WebUI/Views/TracuuVanbandi/_Toolbar.cshtml
@model QLVB.DTO.TracuuVanbandi.ToolbarViewModel
<div class="box ">
	<header>
		<nav class="box-toolbar">           
			<button id="Searchbtn" class="btn btn-success btn-sm btn-primary btn-flat button-box">
				<i class="glyphicon glyphicon-search"></i>&nbsp;Tìm kiếm
			</button>           
			<button id="PrintListVBbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box">
				<i class="glyphicon glyphicon-print"></i>&nbsp;In&nbsp;
			</button>
			<button id="Luutrubtn" style="display:@Model.Luutru;" type="button" class="btn btn-sm btn-primary btn-flat button-box" title="Lưu trữ văn bản">
				<i class="glyphicon glyphicon-folder-close"></i>&nbsp;Cập nhật Lưu trữ
			</button>
		</nav>
	</header>
</div>
<script type="text/javascript">
	$('#Searchbtn').click(function () {
		OpenSearchVBDi();
	});	
	$('#PrintListVBbtn').click(function () {
		var url = '@Url.Action("Export", "Vanbandi")';
		window.location = url;
	});
    $('#Luutrubtn').click(function () {
        var idvanban = GetIdVanban();
	    var url = '@Url.Action("CapnhatVanban", "TracuuLuutru")';
	    url = url + '?idvanban=' + idvanban + '&intloai=2' ;
	    $().redirect(url);
	});
</script>

2.3.4.4.0001/QLVB.WebUI/Views/TracuuVanbandi/_ViewDetailVBDi.cshtml
@(Html.Kendo().Window()
	.Name("ViewDetailVBDi")
	.Draggable()
	.AutoFocus(true)
	.Title("Thông tin văn bản")
	.Resizable()
	.Width(650)
	.Height(490)
	.Visible(false)
	.Actions(actions => actions.Minimize().Maximize().Close())
	.Content(
	@<text>
		<div id="detail-VBDi">
			<div class="box">
				<header>
					<nav style="padding: 3px;">
						<button id="InChitietVBDibtn" type="button" class="btn btn-sm btn-primary btn-flat ">
							<i class="glyphicon glyphicon-print"></i>&nbsp;In
						</button>
						<button id="BackViewDetailVBDibtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>

					</nav>
				</header>
			</div>
			<div id="chitietvanbandi">

			</div>

		</div>
	</text>
	)
)

<script type="text/javascript">
	function CloseViewDetailVBDi() {
		var window = $("#ViewDetailVBDi").data("kendoWindow");
		window.close();
	}
	function OpenViewDetailVBDi(idvanban) {
		LoadVanbanDi(idvanban);
		var window = $("#ViewDetailVBDi").data("kendoWindow");
		window.center();
		window.open();
	}
	function LoadVanbanDi(id) {
		$('#chitietvanbandi').html(" ");
		var url = '@Url.Action("_XemChitietVanban","TracuuVanbandi")';
		url = url + "?id=" + id;
		$('#chitietvanbandi').load(url);
	}
	$('#BackViewDetailVBDibtn').click(function () {
		CloseViewDetailVBDi();
	});

	$('#InChitietVBDibtn').click(function () {
		PrintElement('#chitietvanbandi');
	});
	function OpenTraloiVBDen(idvanbanden) {
		CloseViewDetailVBDi();
		OpenViewDetailVBDen(idvanbanden);
	}

</script>