2.3.4.4.0001/QLVB.WebUI/Controllers/BaocaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLVB.Core.Contract;
using QLVB.Domain.Entities;
using QLVB.DTO;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using QLVB.DTO.Baocao;
using QLVB.Common.Date;
using Microsoft.Reporting.WebForms;
using System.Data;
using QLVB.Common.Utilities;
using OfficeOpenXml;
using System.IO;


namespace QLVB.WebUI.Controllers
{
    public class BaocaoController : Controller
    {
        #region Constructor

        private IBaocaoManager _baocao;

        public BaocaoController(IBaocaoManager baocao)
        {
            _baocao = baocao;
        }

        #endregion Constructor

        #region FormBaocao
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult _Toolbar()
        {
            //ngayhientai.DayOfWeek
            ViewBag.strngaybd = DateTime.Now;
            ViewBag.strngaykt = DateTime.Now.AddDays(7);

            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult _Category()
        {
            CategoryBaocaoViewModel model = _baocao.GetCategory();
            return PartialView(model);
        }


        public ActionResult _DetailSovb(int intloai)
        {
            var sovb = _baocao.GetSovanban(intloai);
            if (intloai == 1)
            {
                // so van ban den
                var donvi = _baocao.GetListDonvi();
                ViewBag.listdonvi = donvi;
            }

            return PartialView(sovb);
        }

        public ActionResult _DetailLoaivb(int intloai)
        {
            var loaivb = _baocao.GetLoaivanban(intloai);

            return PartialView(loaivb);
        }
        public ActionResult _Detailvbdt(int intloai)
        {
            return PartialView();
        }

        #endregion FormBaocao

        #region RequestData

        private SoVanbandenViewModel RequestSovanbanden(string strngaybd, string strngaykt, int? sovb,
           string listidso, bool IsXuly, int iddonvi)
        {
            SoVanbandenViewModel sovbDTO = new SoVanbandenViewModel();
            sovbDTO.idsovanban = sovb;
            sovbDTO.strTungay = strngaybd;
            sovbDTO.strDenngay = strngaykt;
            sovbDTO.IsXuly = IsXuly;
            sovbDTO.iddonvi = iddonvi;
            sovbDTO.strtenphong = _baocao.GetTenPhong(iddonvi, IsXuly);
            sovbDTO.strTenso = _baocao.GetTensovanban(listidso); //_baocao.GetTensovanban((int)sovb);
            sovbDTO.strTendonvi = _baocao.GetTenDonvi();

            List<int> listid = new List<int>();
            string[] split = listidso.Split(',');
            foreach (var s in split)
            {
                try
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        int id = Convert.ToInt32(s);
                        listid.Add(id);
                    }
                }
                catch { }
            }
            sovbDTO.listidso = listid;


            return sovbDTO;
        }

        private SovanbandiViewModel RequestSovanbandi(string strngaybd, string strngaykt, int? sovb, string listidso)
        {
            SovanbandiViewModel sovbDTO = new SovanbandiViewModel();
            sovbDTO.idsovanban = sovb;
            sovbDTO.strTungay = strngaybd;
            sovbDTO.strDenngay = strngaykt;
            sovbDTO.strTenso = _baocao.GetTensovanban(listidso);
            sovbDTO.strTendonvi = _baocao.GetTenDonvi();

            List<int> listid = new List<int>();
            string[] split = listidso.Split(',');
            foreach (var s in split)
            {
                try
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        int id = Convert.ToInt32(s);
                        listid.Add(id);
                    }
                }
                catch { }
            }
            sovbDTO.listidso = listid;

            return sovbDTO;
        }

        private LoaivanbandenViewModel RequestLoaivanbanden(string strngaybd, string strngaykt, int? loaivb, string listidloai)
        {
            LoaivanbandenViewModel loaivbDTO = new LoaivanbandenViewModel();
            loaivbDTO.idloaivanban = loaivb;
            loaivbDTO.strTungay = strngaybd;
            loaivbDTO.strDenngay = strngaykt;
            loaivbDTO.strTenloai = _baocao.GetTenLoaivanban(listidloai);
            loaivbDTO.strTendonvi = _baocao.GetTenDonvi();

            List<int> listid = new List<int>();
            string[] split = listidloai.Split(',');
            foreach (var s in split)
            {
                try
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        int id = Convert.ToInt32(s);
                        listid.Add(id);
                    }
                }
                catch { }
            }
            loaivbDTO.listidloai = listid;

            return loaivbDTO;
        }

        private LoaivanbandiViewModel RequestLoaivanbandi(string strngaybd, string strngaykt, int? loaivb, string listidloai)
        {
            LoaivanbandiViewModel loaivbDTO = new LoaivanbandiViewModel();
            loaivbDTO.idloaivanban = loaivb;
            loaivbDTO.strTungay = strngaybd;
            loaivbDTO.strDenngay = strngaykt;
            loaivbDTO.strTenloai = _baocao.GetTenLoaivanban(listidloai);
            loaivbDTO.strTendonvi = _baocao.GetTenDonvi();

            List<int> listid = new List<int>();
            string[] split = listidloai.Split(',');
            foreach (var s in split)
            {
                try
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        int id = Convert.ToInt32(s);
                        listid.Add(id);
                    }
                }
                catch { }
            }
            loaivbDTO.listidloai = listid;
            return loaivbDTO;
        }

        #endregion RequestData

        #region Report
        public ActionResult Sovanbanden(string strngaybd, string strngaykt, int? sovb,
            string listidso, bool IsXuly, int iddonvi)
        {
            SoVanbandenViewModel sovbDTO = RequestSovanbanden(strngaybd, strngaykt, sovb,
                    listidso, IsXuly, iddonvi);

            var vanban = _baocao.GetSovanbanden(sovbDTO);
            ReportSoVanbandenViewModel model = new ReportSoVanbandenViewModel();
            model.Sovanban = QLVB.Common.Utilities.ListtoDataTableConverter.ToDataTable(vanban);
            model.Thamso = sovbDTO;

            return View(model);
        }

        public ActionResult Sovanbandi(string strngaybd, string strngaykt, int? sovb, string listidso)
        {
            SovanbandiViewModel sovbDTO = RequestSovanbandi(strngaybd, strngaykt, sovb, listidso);

            var vanban = _baocao.GetSovanbandi(sovbDTO);
            ReportSovanbandiViewModel model = new ReportSovanbandiViewModel();
            model.Sovanban = ListtoDataTableConverter.ToDataTable(vanban);
            model.Thamso = sovbDTO;

            return View(model);
        }

        public ActionResult Loaivanbanden(string strngaybd, string strngaykt, int? loaivb, string listidloai)
        {
            LoaivanbandenViewModel loaivbDTO = RequestLoaivanbanden(strngaybd, strngaykt, loaivb, listidloai);


            var vanban = _baocao.GetLoaivanbanden(loaivbDTO);
            ReportLoaivanbandenViewModel model = new ReportLoaivanbandenViewModel();
            model.Loaivanban = ListtoDataTableConverter.ToDataTable(vanban);
            model.Thamso = loaivbDTO;

            return View(model);
        }

        public ActionResult Loaivanbandi(string strngaybd, string strngaykt, int? loaivb, string listidloai)
        {
            LoaivanbandiViewModel loaivbDTO = RequestLoaivanbandi(strngaybd, strngaykt, loaivb, listidloai);


            var vanban = _baocao.GetLoaivanbandi(loaivbDTO);
            ReportLoaivanbandiViewModel model = new ReportLoaivanbandiViewModel();
            model.Loaivanban = ListtoDataTableConverter.ToDataTable(vanban);
            model.Thamso = loaivbDTO;

            return View(model);
        }


        #endregion Report

        #region InphieunhanHS

        public ActionResult InPhieuNhanVBDen(int id)
        //(string strngaybd, string strngaykt, string strngayhientai,
        //string strtendonvi, string strtrichyeu, string strnguoitiepnhan, string strtensovanban)
        {
            PhieunhanVBDenViewModels model = _baocao.GetNoidungPhieuVBDen(id);


            return View(model);
        }

        #endregion InphieunhanHS

        #region Excel

        private int GetLineCount(String text, int columnWidth)
        {
            try
            {
                var lineCount = 1;
                var textPosition = 0;

                while (textPosition <= text.Length)
                {
                    textPosition = Math.Min(textPosition + columnWidth, text.Length);
                    if (textPosition == text.Length)
                        break;

                    if (text[textPosition - 1] == ' ' || text[textPosition] == ' ')
                    {
                        lineCount++;
                        textPosition++;
                    }
                    else
                    {
                        textPosition = text.LastIndexOf(' ', textPosition) + 1;

                        var nextSpaceIndex = text.IndexOf(' ', textPosition);
                        if (nextSpaceIndex - textPosition >= columnWidth)
                        {
                            lineCount += (nextSpaceIndex - textPosition) / columnWidth;
                            textPosition = textPosition + columnWidth;
                        }
                        else
                            lineCount++;

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/InPhieuNhanVBDen.cshtml
@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@model QLVB.DTO.Baocao.PhieunhanVBDenViewModels

@{
    ViewBag.Title = "PhieuNhanHSVBDen";
    Layout = "~/Views/Shared/_Layout_null.cshtml";
}

@Html.MvcReportViewerFluent("Report/rptPhieuNhanHSVBDen.rdlc").ProcessingMode(ProcessingMode.Local).ReportParameters(new { strngaybd = Model.strngaybd, strngaykt = Model.strngaykt, strngayhientai = Model.strngayhientai, tensovanban = Model.strtensovanban, strtendonvi = Model.strtendonvi, strtrichyeu = Model.strtrichyeu, strnguoitiepnhan = Model.strnguoitiepnhan }).Attributes(new { Height = 1000, Width = 800, style = "border: 1px" }).Method(FormMethod.Post)

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/Index.cshtml
@{
    ViewBag.Title = "In báo cáo";    
}

@section header{
    <i class="glyphicon glyphicon-info-sign">&nbsp;</i>In báo cáo
}
@Html.Action("_Toolbar", "Baocao")
<div class="row">
    <div class="col-sm-4 " id="category">
        @Html.Action("_Category")
    </div>
    <div class="col-sm-8 " id="listbaocao">
        @Html.Action("_DetailSovb", new { intloai = 1 })
    </div>
    @Html.Hidden("idbaocao")
    @Html.Hidden("idloai",1)
</div>

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/Loaivanbanden.cshtml
@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@model QLVB.DTO.Baocao.ReportLoaivanbandenViewModel
@{
    ViewBag.Title = "Loaivanbanden";
    Layout = "~/Views/Shared/_Layout_null.cshtml";
}

@Html.MvcReportViewerFluent("Report/rptLoaivanbanden.rdlc").ProcessingMode(ProcessingMode.Local).LocalDataSource("DataSetReport", Model.Loaivanban).ReportParameters(new { strngaybd = Model.Thamso.strTungay, strngaykt = Model.Thamso.strDenngay, tensovanban = Model.Thamso.strTenloai, strtendonvi = Model.Thamso.strTendonvi }).Attributes(new { Height = 600, Width = 1000, style = "border: 1px" }).Method(FormMethod.Post)

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/Loaivanbandi.cshtml
@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@model QLVB.DTO.Baocao.ReportLoaivanbandiViewModel
@{
    ViewBag.Title = "Loaivanbandi";
    Layout = "~/Views/Shared/_Layout_null.cshtml";
}

@Html.MvcReportViewerFluent("Report/rptLoaivanbandi.rdlc").ProcessingMode(ProcessingMode.Local).LocalDataSource("DataSetReport", Model.Loaivanban).ReportParameters(new { strngaybd = Model.Thamso.strTungay, strngaykt = Model.Thamso.strDenngay, tensovanban = Model.Thamso.strTenloai, strtendonvi = Model.Thamso.strTendonvi }).Attributes(new { Height = 600, Width = 1000, style = "border: 1px" }).Method(FormMethod.Post)

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/Sovanbanden.cshtml
@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@model QLVB.DTO.Baocao.ReportSoVanbandenViewModel

@{
    ViewBag.Title = "Sovanbanden";
    Layout = "~/Views/Shared/_Layout_null.cshtml";
}

@Html.MvcReportViewerFluent("Report/rptSovanbanden.rdlc").ProcessingMode(ProcessingMode.Local).LocalDataSource("DataSetReport", Model.Sovanban).ReportParameters(new { strngaybd = Model.Thamso.strTungay, strngaykt = Model.Thamso.strDenngay, tensovanban = Model.Thamso.strTenso, strtendonvi = Model.Thamso.strTendonvi, strtenphong = Model.Thamso.strtenphong }).Attributes(new { Height = 600, Width = 1000, style = "border: 1px" }).Method(FormMethod.Post)

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/Sovanbandi.cshtml
@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@model QLVB.DTO.Baocao.ReportSovanbandiViewModel
@{
    ViewBag.Title = "Sovanbandi";
    Layout = "~/Views/Shared/_Layout_null.cshtml";
}

@Html.MvcReportViewerFluent("Report/rptSovanbandi.rdlc").ProcessingMode(ProcessingMode.Local).LocalDataSource("DataSetReport", Model.Sovanban).ReportParameters(new { strngaybd = Model.Thamso.strTungay, strngaykt = Model.Thamso.strDenngay, tensovanban = Model.Thamso.strTenso, strtendonvi = Model.Thamso.strTendonvi }).Attributes(new { Height = 600, Width = 1000, style = "border: 1px" }).Method(FormMethod.Post)

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/_Category.cshtml
@model QLVB.DTO.Baocao.CategoryBaocaoViewModel

@using Kendo.Mvc.UI.Fluent

@(
 Html.Kendo().TreeView()
    .Name("treeview")
    .Events(events => events.Select("onSelect_treeview"))     
    .ExpandAll(true)
    .Items(item =>
    {       
        item.Add()
        .Text("Văn bản đến")            
        .Id("parentNode")
        .Items(subItem =>
        {
            foreach (var j in Model.Vanbanden)
            {
                subItem.Add().Text(j.strten).Id(j.intid.ToString());
            }
        });
        item.Add()
        .Text("Văn bản đi")
        .Id("parentNode")
        .Items(subItem =>
        {
            foreach (var j in Model.Vanbandi)
            {
                subItem.Add().Text(j.strten).Id(j.intid.ToString());
            }
        });   
        
    })
)
<script type="text/javascript">
    $(window).resize(function () {
        SetTreeViewHeight();
    });
    $(document).ready(function () {
        SetTreeViewHeight();
    })
    function onSelect_treeview(e) {
        var treeview = $("#treeview").getKendoTreeView();
        var text = treeview.dataItem(e.node).text;
        var id = treeview.dataItem(e.node).id;
        SetIdLoaiBC(id);
        LoadDetail(id);
    }
    function LoadDetail(value) {
        var url = "ParentNode";
        switch (value) {
            case "1": // so van ban den               
                url = '@Url.Action("_DetailSovb", "Baocao", new { intloai = 1 })';
                break;
            case "2": // so van ban di
                url = '@Url.Action("_DetailSovb", "Baocao", new { intloai = 2})';
                break;
            case "3": // loai van ban den
                url = '@Url.Action("_DetailLoaivb", "Baocao", new { intloai = 1})';
                break;
            case "4":  // loai van ban di
                url = '@Url.Action("_DetailLoaivb", "Baocao", new { intloai = 2})';
                break;
            case "5":  // van ban den dien tu
                url = '@Url.Action("_Detailvbdt", "Baocao", new { intloai = 1})';
                break;
            case "6":  // van ban di dien tu
                url = '@Url.Action("_Detailvbdt", "Baocao", new { intloai = 2})';
                break;
        }
        if (url != "ParentNode") {
            $('#listbaocao').load(url);
        }        
    }
</script>

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/_DetailLoaivb.cshtml
@model  IEnumerable< QLVB.Domain.Entities.PhanloaiVanban>

<table class="table responsive-table">    
    <tr>
        <th style="width: 10%; text-align: center">
            <b>&nbsp;Chọn</b>
        </th>
        <th style="width: 85%; text-align: left">
            <b>Loại văn bản</b>
        </th>
    </tr>  
   
    @foreach (var p in Model)
    {
        <tr>
            <td style="width: 10%; text-align: center">
                @*@Html.CheckBox(p.intid.ToString(), false, new { onclick = "changeCheck(" + @p.intid + ")", id = p.intid, @class = "clsChon" })*@
                @Html.CheckBox(p.intid.ToString(), false, new { id = p.intid, value = p.intid, @class = "clsChon" })
            </td>
            <td style="width: 85%">
                @Html.Label(p.strtenvanban, new { @class = "font-label" })
            </td>
        </tr>
    }
    
    
</table>

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/_DetailSovb.cshtml
@model IEnumerable<QLVB.Domain.Entities.SoVanban>
@{
    QLVB.DTO.Baocao.ListdonviViewModel listdonvi = ViewBag.listdonvi;
    if (listdonvi != null)
    {        
        @*@Html.CheckBox("IsXuly", listdonvi.IsXuly)*@
        <input checked="checked" id="IsXuly" name="IsXuly" type="checkbox" value="true">
        @Html.Label("In văn bản đã phân xử lý chính", new { @class = "font-label" })
        <br />
        <select id="listdonvi" style="width:300px; ">
            @if (listdonvi.maxLevelDonvi == 0)
            {
                foreach (var m in listdonvi.Donvi)
                {
                    <option value="@m.Id">@m.strtendonvi</option>
                }
            }
            else
            {
                for (int i = 0; i < listdonvi.maxLevelDonvi; i++)
                {
                    {
                        foreach (var m in listdonvi.Donvi)
                        {
                            string strIndent = "";
                            if (m.intlevel <= i)
                            {
                                for (var j = 0; j < i; j++) { strIndent += "&nbsp;&nbsp;&nbsp;"; }
                                <option value="@m.Id">@Html.Raw(strIndent) @m.strtendonvi</option>

                                foreach (var m2 in listdonvi.Donvi)
                                {
                                    if ((m2.intlevel == listdonvi.maxLevelDonvi) && (m2.ParentId == m.Id))
                                    {
                                        string strLastNode = "";
                                        for (var j = 0; j < listdonvi.maxLevelDonvi; j++) { strLastNode += "&nbsp;&nbsp;&nbsp;"; }
                                        <option value="@m2.Id">@Html.Raw(strLastNode) @m2.strtendonvi</option>
                                    }
                                }
                            }
                        }
                    }

                }
            }
        </select>
            <br/><br />
        <script type="text/javascript">
            $("#listdonvi").kendoDropDownList();
        </script>
    }

}

<table class="table responsive-table">
    <tr>
        <th style="width: 10%; text-align: center">
            &nbsp;Chọn
        </th>
        <th style="width: 85%; text-align: left">
            <b>Sổ văn bản</b>
        </th>

    </tr>

    @foreach (var p in Model)
    {
        <tr>
            <td style="width: 10%; text-align: center">
                @*@if (p.intloai == (int)QLVB.Domain.Entities.enumSovanban.intloai.Vanbanden)
                {
                    @Html.CheckBox(p.intid.ToString(), false, new { id = p.intid, value = p.intid, @class = "clsChon" })
                }
                else
                {
                    @Html.CheckBox(p.intid.ToString(), false, new { onclick = "changeCheck(" + @p.intid + ")", id = p.intid, value = p.intid, @class = "clsChon" })
                }*@
                @Html.CheckBox(p.intid.ToString(), false, new { id = p.intid, value = p.intid, @class = "clsChon" })
            </td>
            <td style="width: 85%">
                @Html.Label(p.strten, new { @class = "font-label" })
            </td>

        </tr>
    }
</table>

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/_Detailvbdt.cshtml
van ban dien tu

2.3.4.4.0001/QLVB.WebUI/Views/Baocao/_Toolbar.cshtml
@{
	DateTime strngaybd = ViewBag.strngaybd;
	DateTime strngaykt = ViewBag.strngaykt;
}
<div class="box ">
	<header>
		<nav class="box-toolbar">
			<button id="Printbtn" type="button" class="btn btn-sm btn-primary btn-flat" title="In Báo cáo">
				<i class="glyphicon glyphicon-print"></i>&nbsp;In Báo cáo
			</button>  
            <button id="Excelbtn" type="button" class="btn btn-sm btn-primary btn-flat" title="In Báo cáo">
                <i class="glyphicon glyphicon-download-alt"></i>&nbsp;Xuất Excel
            </button>  
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Từ ngày &nbsp;&nbsp;
			@(Html.Kendo().DatePicker()
						.Name("strngaybd")
						.Value(strngaybd)                        
						.Format("dd/MM/yyyy")
			)
			&nbsp;&nbsp;==>&nbsp;&nbsp;
			@(Html.Kendo().DatePicker()
						.Name("strngaykt")
						.Value(strngaykt)                    
						.Format("dd/MM/yyyy")
			)
		</nav>
	</header>
</div>
<script type="text/javascript">
	$('#Printbtn').click(function () {
		var idloaibc = GetIdLoaiBC();
		var idcheckboxbc = GetIdBaocao();
		var url = GetfrmBC(idloaibc, idcheckboxbc, false);
		open(url, "_blank");
		//if (idcheckboxbc != 0) {
			
		//} else {
		//	SetThongbao("Bạn cần phải chọn loại báo cáo");
		//}
	});
	$('#Excelbtn').click(function () {
	    var idloaibc = GetIdLoaiBC();
	    var idcheckboxbc = GetIdBaocao();
	    var url = GetfrmBC(idloaibc, idcheckboxbc, true);
	    open(url);	    
	});
	function SetIdBaocao(idbaocao) {
		$('#idbaocao').val(idbaocao);
	};
	function GetIdBaocao() {
		return $('#idbaocao').val();
	}
	function SetIdLoaiBC(idloai) {
		$('#idloai').val(idloai);
	}
	function GetIdLoaiBC() {
		return $('#idloai').val();
	}

	function GetfrmBC(idloaibc, idcheckboxbc, IsExcel) {
		var strngaybd = getNgaybd();
		var strngaykt = getNgaykt();
		var url = "";
		url = '@Url.Action("__id__","Report")'.replace('__id__', "");
		switch (idloaibc) {
			case "1": // so van ban den   
				var IsXuly = $('#IsXuly').val();
				if ($('#IsXuly').is(':checked')) {
					IsXuly = true;
				} else {
					IsXuly = false;
				}
				var iddonvi = $('#listdonvi').val();
				var listid = GetAllCheckbox();
				if (IsExcel) {
				    url = '@Url.Action("Sovanbanden_Excel", "Baocao")';
				} else {
				    url = '@Url.Action("Sovanbanden", "Baocao")';
				}						    
				url = url + "?strngaybd=" + strngaybd + "&strngaykt=" + strngaykt;
				url = url + "&sovb=" + idcheckboxbc + "&IsXuly=" + IsXuly + "&iddonvi=" + iddonvi;
				url = url + "&listidso=" + listid;				
				break;
		    case "2": // so van ban di
		        var listid = GetAllCheckbox();
		        if (IsExcel) {
		            url = '@Url.Action("Sovanbandi_Excel", "Baocao")';
		        } else {
		            url = '@Url.Action("Sovanbandi", "Baocao")';
		        }				
		        url = url + "?strngaybd=" + strngaybd + "&strngaykt=" + strngaykt + "&sovb=" + idcheckboxbc;
		        url = url + "&listidso=" + listid;
				break;
		    case "3": // loai van ban den
		        var listid = GetAllCheckbox();
		        if (IsExcel) {
		            url = '@Url.Action("Loaivanbanden_Excel", "Baocao")';
		        } else {
		            url = '@Url.Action("Loaivanbanden", "Baocao")';
		        }				
		        url = url + "?strngaybd=" + strngaybd + "&strngaykt=" + strngaykt + "&loaivb=" + idcheckboxbc;
		        url = url + "&listidloai=" + listid;
				break;
		    case "4":  // loai van ban di
		        var listid = GetAllCheckbox();
		        if (IsExcel) {
		            url = '@Url.Action("Loaivanbandi_Excel", "Baocao")';
		        } else {
		            url = '@Url.Action("Loaivanbandi", "Baocao")';
		        }				
		        url = url + "?strngaybd=" + strngaybd + "&strngaykt=" + strngaykt + "&loaivb=" + idcheckboxbc;
		        url = url + "&listidloai=" + listid;
				break;
			case "5":  // van ban den dien tu
				url = '@Url.Action("Detailvbdt", "Baocao", new { intloai = 1})';
				break;
			case "6":  // van ban di dien tu
				url = '@Url.Action("Detailvbdt", "Baocao", new { intloai = 2})';
				break;
		}
		return url;
	}	
	function getNgaybd() {
		var ngay = $('#strngaybd').val();
		return ngay;
	}
	function getNgaykt() {
		var ngay = $('#strngaykt').val();
		return ngay;
	}
	function changeCheck(idCheck) {
		SetIdBaocao(idCheck);
		$('.clsChon').prop('checked', false)
		var item = '#' + idCheck;
		var value = $(item).prop('checked', true);
	}
	function Checked() {
		//$(".donvi2").prop('checked', $(this).prop('checked'));
		if ($('.clsChon').is(':checked')) {

		}
	}
	function GetAllCheckbox() {
		var listid = "";
		$('.clsChon:checked').each(function () {	        
			listid += this.value + ",";
		});
		return listid;
	}
</script>