2.3.4.4.0001/QLVB.WebUI/Controllers/HosoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLVB.Core.Contract;
using QLVB.Domain.Entities;
using QLVB.DTO;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using QLVB.DTO.Hoso;
using QLVB.Common.Utilities;
using QLVB.Common.Logging;
using QLVB.Common.Date;
using QLVB.Common.Sessions;

namespace QLVB.WebUI.Controllers
{
    public class HosoController : Controller
    {
        #region Constructor

        private IHosoManager _hoso;
        private ILogger _logger;
        private ISessionServices _session;      
        private IEdxmlManager _edxmlManager;
        private ITrucLienthongTinhManager _trucLienthongTinhManager;
        public HosoController(IHosoManager hoso, ILogger logger, ISessionServices session, IEdxmlManager edxmlManager, ITrucLienthongTinhManager trucLienthongTinhManager)
        {
            _hoso = hoso;
            _logger = logger;
            _session = session;
            _edxmlManager = edxmlManager;
            _trucLienthongTinhManager = trucLienthongTinhManager;
        }

        #endregion Constructor

        #region Index

        public ActionResult Index(bool? isBack)
        {
            ViewBag.idnguoinhap = _session.GetUserId();
            if (isBack == true)
            {
                // luu session tim kiem
                //SessionService.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.SearchVBDen);
            }
            else
            {   // khong co isBack (nhan vao menu hoso)
                // thi reset session ve Nosearch
                isBack = false;
                _session.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.NoSearch);
            }
            ViewBag.isBack = isBack;
            return View();
        }
        [ChildActionOnly]
        public ActionResult _ToolbarCongviec()
        {
            return PartialView();
        }

        public ActionResult _CategoryCongviec()
        {
            CategoryCongviecViewModel model = _hoso.GetCategoryCongviec();
            return PartialView(model);
        }

        public ActionResult _ListCongviec(
             bool? isSearch, bool? isBack,
            string strngayhscat, string strxuly, int? intsobd, int? intsokt, string strngayhsbd, string strngayhskt,
            string strtieude, string strhantraloi, int? idlinhvuc
            )
        {
            SearchCongviecViewModel model = new SearchCongviecViewModel();

            model.isSearch = isSearch == true ? true : false;
            model.isBack = isBack == true ? true : false;

            int intPage = 1;
            if (isBack == true)
            {   // tra ve page dang xem khi quay lai
                int _PageType = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchPageType));
                if (_PageType == (int)EnumSession.PageType.HSCV)
                {
                    intPage = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchPageValues));
                }
            }
            model.intPage = intPage;

            if (isSearch == true)
            {
                // khi nhan nut tim kiem thi reset ve Nosearch 
                // de tim theo dieu kien moi
                _session.InsertObject(AppConts.SessionSearchType, EnumSession.SearchType.NoSearch);
            }

            model.strngayhscat = strngayhscat;
            model.strxuly = strxuly;
            model.intsobd = intsobd;
            model.intsokt = intsokt;
            model.strngayhsbd = strngayhsbd;
            model.strngayhskt = strngayhskt;
            model.strtieude = strtieude;
            //model.strxulychinh = strxulychinh;
            model.strhantraloi = strhantraloi;
            model.idlinhvuc = idlinhvuc;

            return PartialView(model);
        }

        public ActionResult ListHoso_Read(
            [DataSourceRequest]DataSourceRequest request,
            string strngayhscat, string strxuly, int? intsobd, int? intsokt, string strngayhsbd, string strngayhskt,
            string strtieude, string strhantraloi, int? idlinhvuc
            )
        {
            int currentPage = request.Page;
            // luu trang dang xem vao session
            _session.InsertObject(AppConts.SessionSearchPageType, EnumSession.PageType.HSCV);
            _session.InsertObject(AppConts.SessionSearchPageValues, currentPage);

            int _SearchType = Convert.ToInt32(_session.GetObject(AppConts.SessionSearchType));

            IEnumerable<ListCongviecViewModel> hoso;

            if (_SearchType == (int)EnumSession.SearchType.SearchHSCV)
            {
                // lay cac gia tri search trong session
                string strSearchValues = _session.GetObject(AppConts.SessionSearchTypeValues).ToString();

                string _strngayhscat = _session.GetStringSearchValues("strngayhscat", strSearchValues);
                string _strxuly = _session.GetStringSearchValues("strxuly", strSearchValues);

                int _intsobd = _session.GetIntSearchValues("intsobd", strSearchValues);
                int _intsokt = _session.GetIntSearchValues("intsokt", strSearchValues);

                string _strngayhsbd = _session.GetStringSearchValues("strngayhsbd", strSearchValues);
                string _strngayhskt = _session.GetStringSearchValues("strngayhskt", strSearchValues);

                string _strtieude = _session.GetStringSearchValues("strtieude", strSearchValues);
                string _strhantraloi = _session.GetStringSearchValues("strhantraloi", strSearchValues);
                //string _strnguoixuly = _session.GetStringSearchValues("strnguoixuly", strSearchValues);

                int? _idlinhvuc = _session.GetIntSearchValues("idlinhvuc", strSearchValues);

                strngayhscat = _strngayhscat;
                strxuly = _strxuly;
                intsobd = _intsobd;
                intsokt = _intsokt;
                strngayhsbd = _strngayhsbd;
                strngayhskt = _strngayhskt;
                strtieude = _strtieude;
                strhantraloi = _strhantraloi;
                idlinhvuc = _idlinhvuc;

            }

            hoso = _GetListCongviec(
                 strngayhscat, strxuly, intsobd, intsokt, strngayhsbd, strngayhskt,
                 strtieude, strhantraloi, idlinhvuc);


            DataSourceResult result = hoso
                                .OrderByDescending(p => p.dtengayhs)
                                .ThenByDescending(p => p.intso)
                                .ToDataSourceResult(request);

            return Json(result);
        }

        private IEnumerable<ListCongviecViewModel> _GetListCongviec(
            string strngayhscat, string strxuly, int? intsobd, int? intsokt, string strngayhsbd, string strngayhskt,
            string strtieude, string strhantraloi, int? idlinhvuc
            )
        {

            return _hoso.GetListCongviec(
                    strngayhscat, strxuly, intsobd, intsokt, strngayhsbd, strngayhskt,
                    strtieude, strhantraloi, idlinhvuc);
        }

        public ActionResult SearchHoso()
        {
            SearchCongviecViewModel model = _hoso.GetViewSearch();
            return PartialView(model);
        }

        public ActionResult _formDeleteHoso()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult DeleteHoso(int id)
        {
            ResultFunction kq = _hoso.DeleteHoso(id);
            return Json(kq.id);
        }
        #endregion Index

        #region ViewDetailHosocongviec

        public ActionResult _ViewDetailHoso()
        {
            return PartialView();
        }

        public ActionResult _XemchitietHoso(int id)
        {
            DetailHosoViewModel model = _hoso.GetDetailHoso(id);
            if (model.idhosocongviec == 0)
            {
                return new ViewResult { ViewName = AppConts.ErrAccessDenied };
            }
            else
            {
                return PartialView(model);
            }
        }

        #endregion ViewDetailHosocongviec

        #region PhanXLVB
        /// <summary>
        /// phan xu ly van ban
        /// </summary>
        /// <param name="id">idvanban</param>
        /// <returns></returns>
        public ActionResult PhanXLVB(int id)
        {
            PhanXLVBViewModel model = _hoso.GetFormPhanXLVB(id);
            if (model.IsQuytrinh)
            {
                ViewBag.message = "Không phân xử lý cho hồ sơ đã có quy trình";
                return View("ErrorHoso");
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult PhanXLVB(int idvanban, FormCollection collection)
        {
            PhanXLVBViewModel hoso = new PhanXLVBViewModel();
            hoso.HosocongviecModel = new Hosocongviec();
            hoso.intidvanban = idvanban;

            string strgiatri = "";
            foreach (string p in collection)
            {
                strgiatri = collection[p];
                if (!string.IsNullOrEmpty(strgiatri))
                {   // lay doi tuong xu ly 
                    if (p == "idhosocongviec") { hoso.HosocongviecModel.intid = Convert.ToInt32(strgiatri); }
                    //if (p == "idvanban") { hoso.intidvanban = Convert.ToInt32(strgiatri); }

                    if (p == "strtieude") { hoso.HosocongviecModel.strtieude = strgiatri; }
                    if (p == "idlinhvuc") { hoso.HosocongviecModel.intlinhvuc = Convert.ToInt32(strgiatri); }

                    if (p == "strnoidung") { hoso.HosocongviecModel.strnoidung = strgiatri; }

                    if (p == "idlanhdaogiaoviec") { hoso.intidlanhdaogiaoviec = Convert.ToInt32(strgiatri); }
                    // chon chuoi stridlanhdaophutrach
                    if (p == "idlanhdaophutrach") { hoso.stridlanhdaophutrach = strgiatri; }

2.3.4.4.0001/QLVB.WebUI/Views/Hoso/XulyHoso.cshtml
@{
	ViewBag.Title = "XulyHoso";
	int idhosocongviec = ViewBag.idhosocongviec;
    string strBack = ViewBag.strBack;
}
@Html.Action("_ToolbarXuly", "Hoso", new { id = idhosocongviec , strBack = strBack })
@Html.Hidden("idhoso", @idhosocongviec)
<div class="row">
	<div class="col-sm-4" id="listdanhsachcanboxuly">
		@Html.Action("_DanhsachNguoixuly", "Hoso", new { idhoso = idhosocongviec })
	</div>
	<div class="col-sm-8">
		@Html.Action("_ThongtinHoso", "Hoso", new { idhoso = idhosocongviec })
	</div>
</div>
<div class="row">
	<div class="col-sm-12" id="chitietthongtinxuly">
		@Html.Action("_ThongtinXuly", "Hoso", new { idhoso = idhosocongviec })
	</div>
</div>

@Html.Action("_ViewPhoihopxuly", "Hoso")
@Html.Action("_ViewDetailVBDen", "Vanbanden")
@Html.Action("_ViewDetailVBDi", "Vanbandi")
@Html.Action("_ViewDetailHoso", "Hoso")
@Html.Partial("_FormLoaiVBLQ")
@Html.Partial("_TamngungQuytrinh",idhosocongviec)

<script type="text/javascript">
    function ReloadCanboxuly() {
        var idhoso = '@idhosocongviec';
        var url = '@Url.Action("_DanhsachNguoixuly", "Hoso")';
        url = url + "?idhoso=" + idhoso;
        $('#listdanhsachcanboxuly').load(url);
    };
    function ReloadThongtinxuly() {
        var idhoso = '@idhosocongviec';
        var url = '@Url.Action("_ThongtinXuly", "Hoso")';
        url = url + "?idhoso=" + idhoso;
        $('#chitietthongtinxuly').load(url);
    };
    function CloseYkienxuly() {
        var window = $("#FormYkienxuly").data("kendoWindow");
        window.close();
    }
    function OpenYkienxuly() {
        var window = $("#FormYkienxuly").data("kendoWindow");
        window.center();
        window.open();
        var idhoso = '@idhosocongviec';
        var url = '@Url.Action("_AddYkien", "Hoso")';
        $('#AddNewYkien').load(url);
    }
    function ClosePhieutrinh() {
        var window = $("#FormPhieutrinh").data("kendoWindow");
        window.close();
    }
    function OpenPhieutrinh(idphieutrinh) {
        var window = $("#FormPhieutrinh").data("kendoWindow");
        window.center();
        window.open();
        var idhoso = '@idhosocongviec';
        var url = '@Url.Action("_Phieutrinh", "Hoso")';
        url = url + "?idphieutrinh=" + idphieutrinh + "&idhoso=" + idhoso;
        $('#detail-Phieutrinh').load(url);
    }
    function CloseVBLQ() {
        var window = $("#FormLoaiVBLQ").data("kendoWindow");
        window.close();
    }
    function OpenVBLQ() {
        var window = $("#FormLoaiVBLQ").data("kendoWindow");
        window.center();
        window.open();
    }
    function CloseHosoVBLQ() {
        var window = $("#HosoVBLQ").data("kendoWindow");
        window.close();
    }
    function OpenHosoVBLQ(idhoso, idloai) {
        var window = $("#HosoVBLQ").data("kendoWindow");
        window.center();
        window.open();
        var url = "";
        switch (idloai) {
            case 1:
                url = '@Url.Action("_HosoVBDenLQ", "Hoso")';
                break;
            case 2:
                url = '@Url.Action("_HosoVBDiLQ", "Hoso")';
                break;
            case 3:
                //url = '@Url.Action("_HosoVBAttachLQ", "Hoso")';
                break;
        }
        url = url + "?idhoso=" + idhoso;
        $('#detail-HosoVBLQ').load(url);
    }
    function CloseViewQuytrinh() {
        var window = $("#ViewQuytrinh").data("kendoWindow");
        window.close();
    }
    function OpenViewQuytrinh(idhoso, update) {
        var window = $("#ViewQuytrinh").data("kendoWindow");
        window.center();
        window.open();
        var url = '@Url.Action("_DisplayQuytrinh", "Hoso")';
        url = url + "?idhoso=" + idhoso;
        url = url + "&update=" + update;
        //$('#detail-Quytrinh').load(url);
    }
    function CloseXulyQuytrinh() {
        var window = $("#XulyQuytrinh").data("kendoWindow");
        window.close();
    }
    function OpenXulyQuytrinh(idhoso) {
        var window = $("#XulyQuytrinh").data("kendoWindow");
        window.center();
        window.open();
        var url = '@Url.Action("_XulyQuytrinh", "Hoso")';
        url = url + "?idhoso=" + idhoso;
        $('#detail-XulyQuytrinh').load(url);
    }
    function CloseChangeQuytrinh() {
        var window = $("#ChangeQuytrinh").data("kendoWindow");
        window.close();
    }
    function OpenChangeQuytrinh(idhoso, update) {
        var window = $("#ChangeQuytrinh").data("kendoWindow");
        window.center();
        window.open();
        var url = '@Url.Action("_ChangeQuytrinh", "Hoso")';
		url = url + "?idhoso=" + idhoso;
		url = url + "&update=" + update;
		$('#detail-ChangeQuytrinh').load(url);
	}
    function CloseDuthaoVB() {
        var window = $("#PhathanhVanban").data("kendoWindow");
        window.close();
    }
    function OpenDuthaoVB(listfile) {
        var window = $("#PhathanhVanban").data("kendoWindow");
        window.center();
        window.open();
        var idhoso = '@idhosocongviec';
        var url = '@Url.Action("_DuthaoVB", "Hoso")';
        url = url + "?idhoso=" + idhoso;
        url = url + "&listfile=" + listfile;
        $('#detail-PhathanhVanban').load(url);
    }
</script>

@(Html.Kendo().Window()
	.Name("FormYkienxuly")
	.Draggable()
	.AutoFocus(true)
	.Modal(true)
	.Title("Ý kiến xử lý")
	.Resizable()
	.Width(600)
	.Height(400)
	.Visible(false)
	.Actions(actions => actions.Minimize().Maximize().Close())
	.Content(
	@<text>
		<div id="AddNewYkien"></div>
	</text>
	)
)

@(Html.Kendo().Window()
	.Name("FormPhieutrinh")
	.Draggable()
	.AutoFocus(true)
	.Modal(true)
	.Title("Phiếu trình")
	.Resizable()
	.Width(600)
	.Height(470)
	.Visible(false)
	.Actions(actions => actions.Minimize().Maximize().Close())
	.Content(
	@<text>
		<div id="detail-Phieutrinh"></div>
	</text>
	)
)

@(Html.Kendo().Window()
	.Name("HosoVBLQ")
	.Draggable()
	.AutoFocus(true)
	.Modal(false)
	.Title("Hồ sơ các văn bản liên quan")
	.Resizable()
	.Width(700)
	.Height(500)
	.Visible(false)
	.Actions(actions => actions.Minimize().Maximize().Close())
	.Content(
	@<text>
		<div id="detail-HosoVBLQ"></div>
	</text>
	)
)

@(Html.Kendo().Window()
	.Name("ViewQuytrinh")
	.Draggable()
	.AutoFocus(true)
	.Modal(false)
	.Title("Quy trình xử lý")
	.Resizable()
	.Width(900)
	.Height(500)
	.Visible(false)
	.Actions(actions => actions.Close())
	.Content(
	@<text>
		<div id="detail-Quytrinh"></div>
	</text>
	)
)
@(Html.Kendo().Window()
	.Name("XulyQuytrinh")
	.Draggable()
	.AutoFocus(true)
	.Modal(false)
	.Title("Quy trình xử lý")
	.Resizable()
	.Width(600)
	.Height(500)
	.Visible(false)
	.Actions(actions => actions.Close())
	.Content(
	@<text>
		<div id="detail-XulyQuytrinh"></div>
	</text>
	)
)
@(Html.Kendo().Window()
	.Name("ChangeQuytrinh")
	.Draggable()
	.AutoFocus(true)
	.Modal(false)
	.Title("Quy trình xử lý")
	.Resizable()
	.Width(900)
	.Height(500)
	.Visible(false)
	.Actions(actions => actions.Maximize().Close())
	.Content(
	@<text>
		<div id="detail-ChangeQuytrinh"></div>
	</text>
	)
)

@(Html.Kendo().Window()
    .Name("PhathanhVanban")
    .Draggable()
    .AutoFocus(true)
    .Modal(false)
    .Title("Dự thảo Văn bản")
    .Resizable()
    .Width(700)
    .Height(300)
    .Visible(false)
    .Actions(actions => actions.Maximize().Close())
    .Content(
    @<text>
        <div id="detail-PhathanhVanban"></div>
    </text>
	)
)

2.3.4.4.0001/QLVB.WebUI/Views/Hoso/_AddYkien.cshtml
@*@model QLVB.DTO.Hoso.AddYkienViewModel*@

<div class="box " id="tbar">
	<header>
		<nav style="padding: 3px;">
			<button id="SaveYkienbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>
			<button id="BackYkienbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>

		</nav>
	</header>
</div>
<div class="row">
	<div id="txtykien" class="col-sm-11">
		<form class="form-horizontal" id="formAddYkien">
			@Html.TextArea("strykienxuly", new { @class = "form-control form-control-window", rows = 15 })
		</form>
	</div>
	<div class="col-sm-4" id="detail-UploadYkien" style="display:none;">        
		<input name="files" id="files" type="file" />
	</div>
</div>


<script type="text/javascript">	
	$('#SaveYkienbtn').click(function () {
		var idhoso = GetIdHoso();
		var strykien = $('#strykienxuly').val();		
		$.ajax(
		{
			type: "POST",
			url: '@Url.Action("_SaveYkien", "Hoso")',
			data: { 'idhoso': idhoso, 'strykien': strykien },
			success: function (idykien) {
				if (idykien == 0) {
					SetThongbao("Lỗi!!!");					
				}
				else {
					$('#txtykien').removeClass("col-sm-11");
					$('#txtykien').addClass("col-sm-6");
					ReloadThongtinxuly();
					EnableUploadYkien(idykien, idhoso);
					$('#detail-UploadYkien').show();					
				}
			},
			dataType: "Json"
		});
	});
	function EnableUploadYkien(idykien, idhoso) {
		var urlykien = "?idykien=" + idykien + "&idhoso=" + idhoso;

		var urlUpload = '@Url.Action("UploadYkien", "File")';
		urlUpload += urlykien;

		var urlRemove = '@Url.Action("RemoveYkien", "File")';
		urlRemove += urlykien;

		$("#files").kendoUpload({
			async: {
				saveUrl: urlUpload,
				removeUrl: urlRemove,
				autoUpload: true
			}
			//template: kendo.template($('#fileTemplate').html())
		});
	};
	$('#BackYkienbtn').click(function () {
		ReloadThongtinxuly();
		CloseYkienxuly();
	});
	
</script>

2.3.4.4.0001/QLVB.WebUI/Views/Hoso/_DuthaoVB.cshtml
@model QLVB.DTO.Hoso.PhathanhVBViewModel

<div class="box " id="tbar">
	<header>
		<nav style="padding: 3px;">                  
			<button id="SavePhathanhbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>
			
			<button id="BackPhathanhbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>
		</nav>
	</header>
</div>

<div id="phathanhvanban">
	<div class="row">
		<div class="col-sm-12">
			<span id="ketqua" class="validation-summary-valid"></span>
			<form class="form-horizontal" id="formDuthaoVanban" method="post" action="@Url.Action("_DuthaoVB", "Hoso")">
				@Html.HiddenFor(m=>m.idhoso)
				@Html.HiddenFor(m=>m.idvanbanden)
                @Html.HiddenFor(m=>m.strlistfile)
				<div class="form-group form-group-window">
					<label class="col-sm-3 control-label"><span style="color:red">*&nbsp;</span>Loại văn bản</label>
					<div class="col-sm-5">
						@(Html.Kendo().DropDownList()
                                    .Name("intidloaivanban")
									.BindTo(Model.PhanloaiVanban)
									.DataTextField("strtenvanban")
									.DataValueField("intid")
									//.Value(Model.intidloaivanban.ToString())
									.HtmlAttributes(new { @style = "width:100%;" })
						)

					</div>
				</div>

				<div class="form-group form-group-window">
					<label class="col-sm-3 control-label"><span style="color:red">*&nbsp;</span>Trích yếu</label>
					<div class="col-sm-7">
						@Html.TextAreaFor(u => u.strtrichyeu, new
								{
									@class = "form-control",
									@rows = "4",
									@Value = Model.strtrichyeu
								})
					</div>
				</div>

				<div class="form-group form-group-window">
					<label class="col-sm-3 control-label"><span style="color:red">*&nbsp;</span>Người duyệt</label>
					<div class="col-sm-5">						
                        @(Html.Kendo().DropDownList()
                                    .Name("idnguoiduyet")
                                    .BindTo(Model.Nguoiky)
                                    .DataTextField("strhoten")
                                    .DataValueField("intid")                                    
                                    .HtmlAttributes(new { @style = "width:100%;" })
                        )
					</div>
				</div>
								

			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#BackPhathanhbtn').click(function () {
		CloseDuthaoVB();
	})
	$('#SavePhathanhbtn').click(function () {
		var validatable = $("#formDuthaoVanban").kendoValidator({
			rules: {                
				trichyeu: function (input) {
					if (input.is("[name=strtrichyeu]")) {
						return $('#strtrichyeu').val() != "";
					}
					return true;
				},
				nguoiky: function (input) {
					if (input.is("[name=strnguoiky]")) {
						return $('#strnguoiky').val() != "";
					}
					return true;
				}                
			},
			messages: {                
				trichyeu: "*",
				nguoiky: "*"                
			}            
		}).data("kendoValidator");

		if (validatable.validate()) {           
			SubmitFormAddVanban();            
		}
	})
	function SubmitFormAddVanban() {
		var form = $("#formDuthaoVanban").serialize();
		$.ajax(
		{
			type: "POST",
			url: '@Url.Action("_DuthaoVB", "Hoso")',
			data:  form ,
			success: function (data) {
				if (data == 1) {
				    ReloadThongtinxuly();
				    CloseDuthaoVB();
				}
				else {
					//OpenXulyQuytrinh(idhoso);
					SetThongbao(data);
				}
			}
		});
	}
</script>

2.3.4.4.0001/QLVB.WebUI/Views/Hoso/_Phoihopxuly.cshtml
@model QLVB.DTO.Hoso.PhoihopXulyViewModel


<div class="box">
	<header>
		<nav style="padding: 3px;">
			<button id="SubmitPhoihopxulybtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>			
			<button id="ClosePhoihopxulybtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>

		</nav>
	</header>
</div>
<span id="ketqua" class="validation-summary-valid"></span>
<div style="height:400px ;width: 100%; overflow-y: scroll;">
	<div class="row">
		<div class="col-xs-12">
			<form class="form-horizontal" id="formAddPhoihopxuly">
				@Html.Hidden("idhoso", Model.idhoso)
				<table class="table table-condensed responsive-table" style="width: 100%">
					@for (int i = 0; i <= Model.maxLevelDonvi; i++)
					{
						foreach (var dv in Model.donvi)
						{
							string strIndent = "";
							if (dv.intlevel == i)
							{
								<tr>
									<td colspan="2">
										@for (var j = 0; j < i; j++) { strIndent += "&nbsp;&nbsp;&nbsp;"; }										
										@Html.Raw(strIndent)<b>@dv.strtendonvi</b>
									</td>
								</tr>
								foreach (var c in Model.canbo)
								{
									if (dv.Id == c.intiddonvi)
									{
										<tr>
											<td style="width:50px;text-align:center;">
												@if ((c.IsCheck == true) & (c.IsPhoihopxuly == false))
												{
													@Html.CheckBox(c.intid.ToString(), c.IsCheck, new { disabled = "disabled" })
												}
												else
												{
													@Html.CheckBox(c.intid.ToString(), c.IsCheck)
												}
											</td>
											<td>
												@c.strhoten
											</td>
										</tr>
									}
								}

								@*foreach (var d2 in Model.donvi)
								{
									if ((d2.intlevel == Model.maxLevelDonvi) && (d2.ParentId == dv.Id))
									{
										string strLastNode = "";
										for (var j = 0; j <= Model.maxLevelDonvi; j++) { strLastNode += "&nbsp;&nbsp;&nbsp;"; }
										<tr>
											<td colspan="2">
												@Html.Raw(strLastNode)												
												<b>@d2.strtendonvi</b>
											</td>
										</tr>

										foreach (var c in Model.canbo)
										{
											if (d2.Id == c.intiddonvi)
											{
												<tr>
													<td style="width:50px;text-align:center;">
														@if ((c.IsCheck == true) & (c.IsPhoihopxuly == false))
														{
															@Html.CheckBox(c.intid.ToString(), c.IsCheck, new { disabled = "disabled" })
														}
														else
														{
															@Html.CheckBox(c.intid.ToString(), c.IsCheck)
														}
   
													</td>
													<td>
														@c.strhoten
													</td>
												</tr>
											}
										}

									}
								}*@


							}
						}
					}
				</table>
			</form>
		</div>
	</div>

</div>
<script type="text/javascript">
	$('#ClosePhoihopxulybtn').click(function () {
		CloseViewPhoihopxuly();
	});
	$("#SubmitPhoihopxulybtn").click(function () {
		$.ajax(
		{
			type: "POST",
			url: '@Url.Action("_SavePhoihopxuly", "Hoso")',
		    data: $("#formAddPhoihopxuly").serialize(),
			success: function (data) {
				if (data == 1) {
				    CloseViewPhoihopxuly();
				    // reload canbo xuly hoso
				    ReloadCanboxuly();
				    ReloadThongtinxuly();
				}
				else {
				    SetThongbao("Lỗi!!!");
				}
			},
			dataType: "Json"
		});
	});
	
</script>