2.3.4.4.0001/QLVB.WebUI/Controllers/QuytrinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLVB.Domain.Entities;
using QLVB.Domain.Abstract;
using QLVB.DTO;
using QLVB.DTO.Quytrinh;
using QLVB.Core.Contract;

namespace QLVB.WebUI.Controllers
{
    public class QuytrinhController : Controller
    {
        #region Constructor

        private IQuytrinhManager _quytrinh;
        public QuytrinhController(IQuytrinhManager quytrinh)
        {
            _quytrinh = quytrinh;
        }

        #endregion Constructor

        #region Index
        public ActionResult Index(int? id)
        {
            if (QLVB.Common.Utilities.AppSettings.IsWorkflow)
            {
                ViewBag.id = (id > 0) ? id : 0;
                string strtenquytrinh = _quytrinh.GetFlowChartName(ViewBag.id);
                ViewBag.strtenquytrinh = (!string.IsNullOrEmpty(strtenquytrinh)) ? strtenquytrinh : "Quy trình xử lý";
                return View();
            }
            else
            {
                return View("Error");
            }
        }


        public ActionResult _Listloaiquytrinh()
        {
            ListLoaiQuytrinhViewModel model = _quytrinh.GetListLoaiQuytrinh();
            return PartialView(model);
        }

        public ActionResult _Chitietquytrinh(int? id)
        {
            string jsFlowchart = _quytrinh.ReadFlowChart((int)id);
            ViewBag.jsFlowchart = jsFlowchart;
            ViewBag.idquytrinh = (int)id;
            return PartialView();
        }
        #endregion Index

        #region Loai quy trinh

        public ActionResult _formEditLoaiquytrinh(int id)
        {
            EditLoaiQuytrinhViewModel model = _quytrinh.GetEditLoaiQuytrinh(id);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult SaveLoaiquytrinh(int id, string strten)
        {
            ResultFunction kq = _quytrinh.SaveLoaiQuytrinh(id, strten);
            if (kq.id == (int)ResultViewModels.Success)
            {
                return Json(kq.id);
            }
            else
            {
                return Json(kq.message);
            }
        }
        public ActionResult _formDeleteLoaiquytrinh(int id)
        {
            return PartialView();
        }

        #endregion Loai quy trinh


        #region Quy trinh

        public ActionResult _formEditQuytrinh(int id)
        {
            EditQuytrinhViewModel model = _quytrinh.GetEditQuytrinh(id);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Savequytrinh(EditQuytrinhViewModel model, string dteThoigianApdung)
        {
            model.dteThoigianApdung = QLVB.Common.Date.DateServices.FormatDateEn(dteThoigianApdung);

            ResultFunction kq = _quytrinh.SaveQuytrinh(model);
            if (kq.id == (int)ResultViewModels.Success)
            {
                return Json(kq.id);
            }
            else
            {
                return Json(kq.message);
            }
        }

        [HttpPost]
        public ActionResult SaveFlowChart(int id, string strjson)
        {
            ResultFunction kq = _quytrinh.SaveFlowChart(id, strjson);
            if (kq.id == (int)ResultViewModels.Success)
            {
                return Json(kq.id);
            }
            else
            {
                return Json(kq.message);
            }
        }

        [HttpPost]
        public ActionResult DeleteFlowChart(int id)
        {
            ResultFunction kq = _quytrinh.DeleteFlowChart(id);
            if (kq.id == (int)ResultViewModels.Success)
            {
                return Json(kq.id);
            }
            else
            {
                return Json(kq.message);
            }
        }

        [HttpPost]
        public ActionResult SaveVersion(int id)
        {
            ResultFunction kq = _quytrinh.SaveVersion(id);
            return Json(kq.message);
        }
        #endregion Quy trinh

        #region Thongtin xuly

        public ActionResult _formThongtinXuly(int idquytrinh, string NodeId)
        {
            EditThongtinXulyViewModel model = _quytrinh.GetThongtinXuly(idquytrinh, NodeId);
            return PartialView(model);
        }


        [HttpPost]
        public ActionResult _SaveThongtinXuly(EditThongtinXulyViewModel model)
        {
            ResultFunction kq = _quytrinh.SaveThongtinXuly(model);
            if (kq.id == (int)ResultViewModels.Success)
            {
                return Json(kq.id);
            }
            else
            {
                return Json(kq.message);
            }
        }


        public JsonResult GetCanbothuchien(int? iddonvi)
        {
            if (iddonvi != null)
            {
                var canbo = _quytrinh.GetListCanbo((int)iddonvi);
                return Json(canbo, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return null;
            }
        }
        #endregion Thongtin xuly

        #region Version

        public ActionResult Phienban(int id)
        {
            ViewBag.id = id;
            ViewBag.strtenquytrinh = _quytrinh.GetFlowChartName(id);
            return View();
        }

        [ChildActionOnly]
        public ActionResult CategoryVersion(int id)
        {
            CategoryNgayViewModel model = _quytrinh.GetCategoryNgay(id);
            model.idquytrinh = id;
            return PartialView(model);
        }

        public ActionResult ChitietVersion(int id, string ngay)
        {
            string jsFlowchart = _quytrinh.ReadFlowChartVersion(id, ngay);
            ViewBag.jsFlowchart = jsFlowchart;
            ViewBag.idquytrinh = id;
            ViewBag.strngay = ngay;
            return PartialView();
        }
        [HttpPost]
        public ActionResult _LoadThongtinXuly(int idquytrinh, string strngay, string NodeId)
        {
            ViewThongtinXulyViewModel model = _quytrinh.LoadThongtinXuly(idquytrinh, strngay, NodeId);
            return Json(model);
        }

        #endregion Version

    }
}

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/CategoryVersion.cshtml
@model QLVB.DTO.Quytrinh.CategoryNgayViewModel

@(
 Html.Kendo().TreeView()
    .Name("treeview")
    .Events(events => events.Select("onSelect_treeview"))
    .HtmlAttributes(new { @class = "text-color-black" })
    .ExpandAll(true)
    .Items(item =>
        item.Add()
            .Text("Ngày phiên bản")            
            .Id("parentNode")
            .Items(subItem =>
            {
                foreach( var p in Model.ListNgay)
                {
                    subItem.Add()
                        .Text(p)
                        .Id(p);
                }
            })
        )
    )

<script type="text/javascript">
    $(window).resize(function () {
        SetTreeViewHeight();
    });
    $(document).ready(function () {
        SetTreeViewHeight();
    })
    function onSelect_treeview(e) {
        var treeview = $("#treeview").getKendoTreeView();
        var text = treeview.dataItem(e.node).text;
        var id = treeview.dataItem(e.node).id;
        //console.log(id);
        if (id != "parentNode") {
            var url = '@Url.Action("ChitietVersion", "Quytrinh")';
            url = url + '?id=' + '@Model.idquytrinh' + '&ngay=' + id;            
            $('#detail-quytrinh').load(url);
        }
    }

</script>

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/Index.cshtml
@{
    ViewBag.Title = "Index";
    int idquytrinh = ViewBag.id;
}

@section header{
    <i class="glyphicon glyphicon-retweet">&nbsp;</i>@ViewBag.strtenquytrinh
}

<div class="row">
    <div class="col-sm-3" id="loaiquytrinh">
        @Html.Action("_Listloaiquytrinh")
    </div>
    <div class="col-sm-9" id="detail-quytrinh">
        @Html.Action("_Chitietquytrinh", new { id = idquytrinh })
    </div>
    @Html.Hidden("idloaiQT")
    @Html.Hidden("idQuytrinh",idquytrinh)
</div>

<script type="text/javascript">
    function SetIdLoaiQT(idloaiQT) {
        $('#idloaiQT').val(idloaiQT);
    }
    function GetIdLoaiQT() {
        var id = $('#idloaiQT').val();
        return id;
    }
    function SetIdQuytrinh(idQuytrinh) {
        $('#idQuytrinh').val(idQuytrinh);
    }
    function GetIdQuytrinh() {
        var id = $('#idQuytrinh').val();
        return id;
    }
    function CloseEditLoaiQT() {
        var window = $("#EditLoaiQT").data("kendoWindow");
        window.close();
    }
    function OpenEditLoaiQT() {
        var window = $("#EditLoaiQT").data("kendoWindow");
        window.center();
        window.open();
    }
    $("#AddLoaiQTbtn").bind("click", function () {
        var id = 0;
        var url = '@Url.Action("_formEditLoaiquytrinh", "Quytrinh")';
        url = url + '?id=' + id;
        $('#detail-editLoaiQT').load(url);
        OpenEditLoaiQT();
    });
    $("#EditLoaiQTbtn").bind("click", function () {
        var id = GetIdLoaiQT();
        if (id != 0) {
            var url = '@Url.Action("_formEditLoaiquytrinh", "Quytrinh")';
            url = url + '?id=' + id;
            $('#detail-editLoaiQT').load(url);
            OpenEditLoaiQT();
        } else {
            SetThongbao("Bạn chưa chọn loại quy trình");
        }
    });
    $("#DeleteLoaiQTbtn").bind("click", function () {
        @*var id = GetIdLoaiQT();
        if (id != 0) {
            var url = '@Url.Action("_formDeleteLoaiquytrinh", "Quytrinh")';
            url = url + '?id=' + id;
            $('#detail-editLoaiQT').load(url);
            OpenEditLoaiQT();
        } else {
            SetThongbao("Bạn chưa chọn loại quy trình");
        }*@
    });
    function RefreshLoaiQT() {
        @*var url = '@Url.Action("_Listloaiquytrinh", "Quytrinh")';
        $('#loaiquytrinh').load(url);*@
        window.location = '@Url.Action("Index","Quytrinh")';
    }

    function CloseEditQuytrinh() {
        var window = $("#EditQuytrinh").data("kendoWindow");
        window.close();
    }
    function OpenEditQuytrinh() {
        var window = $("#EditQuytrinh").data("kendoWindow");
        window.center();
        window.open();
    }
    $("#AddQuytrinhbtn").bind("click", function () {        
        var id = 0;        
        var url = '@Url.Action("_formEditQuytrinh", "Quytrinh")';
        url = url + '?id=' + id;            
        $('#detail-editQuytrinh').load(url);
        OpenEditQuytrinh();
    });

    $("#EditQuytrinhbtn").bind("click", function () {        
        var id = GetIdQuytrinh();
        if (id != 0) {
            var url = '@Url.Action("_formEditQuytrinh", "Quytrinh")';
            url = url + '?id=' + id;            
            $('#detail-editQuytrinh').load(url);
            OpenEditQuytrinh();
        } else {
            SetThongbao("Bạn chưa chọn quy trình");
        }
    });

    //==================================
    //jsPlumb.ready(function () {
    //    jsPlumb.importDefaults({
    //        ConnectionOverlays: [
    //            ["Arrow", { width: 10, length: 20, location: 1, id: "arrow" }]
    //        ],
    //        PaintStyle: {
    //            lineWidth: 2,
    //            strokeStyle: "#5c96bc"
    //        },
    //        HoverPaintStyle: { strokeStyle: "#1e8151", lineWidth: 2 },
    //        Connector: ["Flowchart", { stub: [5, 5], midpoint: 0.4, cornerRadius: 3, alwaysRespectStubs: true }],
    //        anchors: "Continuous",
    //        Endpoints: [["Rectangle", { width: 10, height: 10 }], ["Dot", { radius: 5 }]],
    //        EndpointStyles: [{ fillStyle: "#225588" }, { fillStyle: "#558822" }]
    //    });
    //    jsPlumb.bind('connection', function (info) {
    //        var idlabel = SetLabelId(info.connection.id);
    //        var labeltext = SetLabelText('Có/Không', idlabel);
    //        info.connection.addOverlay(["Label", { label: labeltext, location: 0.25, id: idlabel, cssClass: "aLabel context-menu-label" }]);
    //    });
    //    console.log("jsplumb ready");
    //    //DisplayFlowchart();
    //});
</script>

@(Html.Kendo().Window()
    .Name("EditLoaiQT")
    .Draggable()
    .AutoFocus(true)
    .Title("Cập nhật Loại quy trình")
    .Resizable()
    .Width(500)
    .HtmlAttributes(new { style = "height:100%;" })
    .Visible(false)
    .Actions(actions => actions.Minimize().Maximize().Close())
    .Content(
    @<text>
        <div id="detail-editLoaiQT">
        </div>
    </text>
    )
)

@(Html.Kendo().Window()
    .Name("EditQuytrinh")
    .Draggable()
    .AutoFocus(true)
    .Title("Cập nhật Quy trình")
    .Resizable()
    .Width(500)
    .HtmlAttributes(new { style = "height:100%;" })
    .Visible(false)
    .Actions(actions => actions.Minimize().Maximize().Close())
    .Content(
    @<text>
        <div id="detail-editQuytrinh">
        </div>
    </text>
    )
)

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/Phienban.cshtml
@{
    ViewBag.Title = "Phienban";
    int idquytrinh = ViewBag.id;
}

@section header{
    <i class="glyphicon glyphicon-retweet">&nbsp;</i>@ViewBag.strtenquytrinh
}
<div class="box ">
    <header>
        <nav class="box-toolbar">
            <button id="Backbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>
        </nav>
    </header>
</div>
<div class="row">
    <div class="col-sm-3" id="category-ngay">
        @Html.Action("CategoryVersion", new { id= idquytrinh })
    </div>
    <div class="col-sm-9" id="detail-quytrinh">
        @Html.Action("ChitietVersion", new { id = 0 })
    </div>
   
</div>
<script type="text/javascript">
    $('#Backbtn').click(function () {
        var url = '@Url.Action("Index", "Quytrinh", new { id =idquytrinh })';
        window.location = url;
    });
</script>

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/_Listloaiquytrinh.cshtml
@model QLVB.DTO.Quytrinh.ListLoaiQuytrinhViewModel

@using QLVB.DTO
<div class="box ">
    <header>
        <nav class="box-toolbar">
            <button id="AddLoaiQTbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box" data-original-title="" title="Thêm mới loại quy trình"><i class="glyphicon glyphicon-plus"></i>&nbsp;Thêm</button>
            <button id="EditLoaiQTbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box" data-original-title="" title=""><i class="glyphicon glyphicon-pencil"></i>&nbsp;Sửa</button>
            @*<button id="DeleteLoaiQTbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box" data-original-title="" title=""><i class="glyphicon glyphicon-trash"></i>&nbsp;Xóa</button>*@
            <button id="AddQuytrinhbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box" data-original-title="" title="Thêm mới quy trình"><i class="glyphicon glyphicon-plus"></i>&nbsp;Thêm QT</button>
            <button id="EditQuytrinhbtn" type="button" class="btn btn-sm btn-primary btn-flat button-box" data-original-title="" title="Thêm mới quy trình"><i class="glyphicon glyphicon-plus"></i>&nbsp;Sửa QT</button>
        </nav>
    </header>
</div>

@(Html.Kendo().PanelBar()
        .Name("panelbar")
        .ExpandMode(PanelBarExpandMode.Multiple)        
        .Items(panelbar =>
        {           
            foreach (var q in Model.LoaiQuytrinh)
            {
                panelbar.Add().Text(q.strtenloaiquytrinh).HtmlAttributes(new { id = "loai_" + q.intid })
                    .Expanded(true)
                    .Items(cat =>
                    {
                        foreach (var p in Model.Quytrinh)
                        {
                            if (p.idloai == q.intid)
                            {
                                cat.Add().Text(p.strtenquytrinh).HtmlAttributes(new { id = p.intid });    
                            }                            
                        }
                    });
            }
        })
        .Events(events => events.Select("select"))
)
<script type="text/javascript">
    function select(e) {
        var id = e.item.id;
        var loai = "loai_";
        if (id.indexOf(loai) > -1) {
            var idloai = id.substring(loai.length);
            SetIdLoaiQT(idloai);
        } else {
            SetIdQuytrinh(id);
            //var url = '@Url.Action("_Chitietquytrinh", "Quytrinh", (new { id = "__id__" }))'.replace('__id__', id);
            //$('#detail-quytrinh').load(url);
            //var url = '@Url.Action("Index", "Quytrinh", (new { id = "__id__" }))'.replace('__id__', id);
            //window.location = url;
        }
    }

</script>

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/_formDeleteLoaiquytrinh.cshtml
asdggsda

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/_formEditLoaiquytrinh.cshtml
@model QLVB.DTO.Quytrinh.EditLoaiQuytrinhViewModel

<div class="box">
    <form class="form-horizontal" id="formEditLoaiQT">
        <span id="ketquaSaveLoaiQT" class="validation-summary-valid"></span>
        <header>
            <nav style="padding: 3px;">
                <button id="SaveLoaiQTbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>
                <button id="BackLoaiQTbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Bỏ qua</button>
            </nav>
        </header>

        @Html.HiddenFor(m => m.intid)
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.strtenloaiquytrinh, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.strtenloaiquytrinh, new { @class = "form-control form-control-window", placeholder = "Tên Loại quy trình" })
            </div>
        </div>
        
    </form>
</div>
<script type="text/javascript">

    $("#SaveLoaiQTbtn").click(function () {
        var validatable = $("#formEditLoaiQT").kendoValidator().data("kendoValidator");
        if (validatable.validate()) {            
            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveLoaiquytrinh", "Quytrinh")',
                dataType: "json",
                data: { id: '@Model.intid',strten:$('#strtenloaiquytrinh').val()},
                success: function (data) {
                    if (data == 1) {
                        ShowResult("ketquaSaveLoaiQT", "Cập nhật thành công");
                        RefreshLoaiQT();
                    }
                    else {
                        ShowResult("ketquaSaveLoaiQT", "Lỗi !!!");
                        //RefreshGrid();
                    }
                },
            });
        }
    });
    $('#BackLoaiQTbtn').click(function () {
        CloseEditLoaiQT();
    })
    
</script>

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/_formEditQuytrinh.cshtml
@model QLVB.DTO.Quytrinh.EditQuytrinhViewModel
@*@using QLVB.DTO*@
@{
    SelectList ListQuytrinh = new SelectList(Model.LoaiQuytrinh, "intid", "strtenloaiquytrinh");
    DateTime dteNow = DateTime.Now;
}

<div class="box">
    <form class="form-horizontal" id="formEditQuytrinh">
        <span id="ketquaSaveQuytrinh" class="validation-summary-valid"></span>
        <header>
            <nav style="padding: 3px;">
                <button id="SaveQuytrinhbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>
                <button id="BackQuytrinhbtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>
            </nav>
        </header>

        @Html.HiddenFor(m => m.intid)        
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.idloai, new { @class = "control-label col-sm-3" })
            <div class="col-sm-6">
                <td>@Html.DropDownListFor(m => m.idloai, ListQuytrinh, new { @class = "form-control form-control-window" })</td>
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.strtenquytrinh, new { @class = "control-label col-sm-3" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.strtenquytrinh, new { @class = "form-control form-control-window", placeholder = "Tên Loại quy trình" })
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.intSongay, new { @class = "control-label col-sm-3" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.intSongay, new { @class = "form-control form-control-window", placeholder = "0" })
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.dteThoigianApdung, new { @class = "control-label col-sm-3" })
            <div class="col-sm-6">                
                @(Html.Kendo().DatePicker()
                        .Name("dteThoigianApdung")
                        .Value(Model.dteThoigianApdung)
                        .HtmlAttributes(new { style = "width:100%;" })
                        .Format("dd/MM/yyyy")
                )
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.IsActive, new { @class = "control-label col-sm-3" })
            <div class="col-sm-6">
                @Html.CheckBoxFor(m => m.IsActive)
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">

    $("#SaveQuytrinhbtn").click(function () {
        var validatable = $("#formEditQuytrinh").kendoValidator().data("kendoValidator");
        if (validatable.validate()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Savequytrinh", "Quytrinh")',
                dataType: "json",
                data: $('#formEditQuytrinh').serialize(),
                success: function (data) {
                    if (data == 1) {
                        ShowResult("ketquaSaveQuytrinh", "Cập nhật thành công");
                        RefreshLoaiQT();
                    }
                    else {
                        ShowResult("ketquaSaveQuytrinh", "Lỗi !!!");                        
                    }
                },
            });
        }
    });
    $('#BackQuytrinhbtn').click(function () {
        CloseEditQuytrinh();
    })

</script>

2.3.4.4.0001/QLVB.WebUI/Views/Quytrinh/_formThongtinXuly.cshtml
@model QLVB.DTO.Quytrinh.EditThongtinXulyViewModel

<div class="box">
    <form class="form-horizontal" id="formEditXuly">
        <span id="ketquaSaveXuly" class="validation-summary-valid"></span>
        <header>
            <nav style="padding: 3px;">
                <button id="SaveXulybtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Ghi nhận</button>
                <button id="BackXulybtn" type="button" class="btn btn-sm btn-primary btn-flat " data-original-title="" title=""><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;Quay lại</button>
            </nav>
        </header>
        @Html.HiddenFor(m => m.idquytrinh)
        @Html.HiddenFor(m=>m.strtenquytrinh)
        @Html.HiddenFor(m => m.intidNode)
        @Html.HiddenFor(m => m.strNodeId)
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.intDonvi, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">                
                @(Html.Kendo().DropDownList()
                    .Name("intDonvi")
                    .HtmlAttributes(new { style = "width:100%;" })
                    .OptionLabel("Đơn vị thực hiện...")
                    .DataTextField("strtendonvi")
                    .DataValueField("intid")
                    .BindTo(Model.listDonvi)
                )
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.intCanbo, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                <script>
                    function filterDonvi() {                        
                        return {
                            iddonvi: $("#intDonvi").val()
                        };
                    }
                </script>
               
                @(Html.Kendo().DropDownList()
                    .Name("intCanbo")
                    .HtmlAttributes(new { style = "width:100%;" })
                    .OptionLabel("Cán bộ thực hiện...")
                    .DataTextField("strhoten")
                    .DataValueField("intid")
                    .DataSource(source =>
                    {
                        source.Read(read =>
                        {
                            read.Action("GetCanbothuchien", "Quytrinh")
                                .Data("filterDonvi");
                        })
                         .ServerFiltering(true);
                    })
                    .Enable(false)
                    .AutoBind(false)
                    .CascadeFrom("intDonvi")
                )               

            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.LoaiVaitro, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">               
                @Html.EnumDropDownListFor(m => m.LoaiVaitro , new { @class = "form-control form-control-window" })
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.intSoNgay, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.intSoNgay, new { @class = "form-control form-control-window", placeholder = "0" })
            </div>
        </div>
        @*<div class="form-group form-group-window">
            @Html.LabelFor(m => m.IsNext, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                @Html.CheckBoxFor(m => m.IsNext)
            </div>
        </div>*@
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.IsHoanthanh, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                @Html.CheckBoxFor(m => m.IsHoanthanh)
            </div>
        </div>
        <div class="form-group form-group-window">
            @Html.LabelFor(m => m.IsXulyDongthoi, new { @class = "control-label col-sm-4" })
            <div class="col-sm-6">
                @Html.CheckBoxFor(m => m.IsXulyDongthoi)
            </div>
        </div>
    </form>

</div>
<script type="text/javascript">
   
    $("#SaveXulybtn").click(function () {
        var validatable = $("#formEditXuly").kendoValidator().data("kendoValidator");
        if (validatable.validate()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("_SaveThongtinXuly", "Quytrinh")',
                dataType: "json",
                data: $('#formEditXuly').serialize(),
                success: function (data) {
                    if (data == 1) {
                        ShowResult("ketquaSaveXuly", "Cập nhật thành công");
                    }
                    else {
                        ShowResult("ketquaSaveXuly", data);
                    }
                },
            });
        }
    });
    $('#BackXulybtn').click(function () {
        CloseThongtinXuly()
    })
</script>